name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          choco install mingw --version=12.2.0 -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Compile program
        run: gcc main.c -o myapp.exe -mwindows

      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: myapp.exe
